# Generated by Django 4.2.16 on 2025-02-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryrecord',
            name='book',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='libraryrecord',
            name='student',
            field=models.IntegerField(),
        ),
    ]
